### ISSUE TITLE
dns delivery compile error

### ISSUE THREAD

**Issue by ghost** [Arno0x/DNSDelivery#1]
hi thanks for this great job, when i try to compile the dnsdelivery.cs it gives me this error: "DnsResolver does not exist in this contest"!!

**Comment by Arno0x** [comment]
Hi, make sure you also have the dnsResolver.cs file in the same directory and compile both files using the following command line:
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe /unsafe /out:dnsdelivery.exe ***.cs**
